/*
* DO NOT MODIFY THIS COMMENT
* Generated by devmate
* Test model: 32623247-420f-4c3e-9a4d-0ae2c3c33abf
*/

using System;
using System.Collections.Generic;
using Xunit;

namespace ServerTests
{
	public class StartDefaultTestCase
	{
#region Theories
		[Theory]
		[ClassData(typeof(ExpectedReturnValueTests))]
		public void StartDefaultTest(NoThrowTestData data)
		{
			data.ObjectUnderTest.StartDefault();
		}
#endregion

#region Types
//=========================================================================================================================
//Please modify this section only in the Modeleditor not here in the code, because otherwise it will cause merge conflicts!
//=========================================================================================================================
		public struct NoThrowTestData
		{
			public string Name;
			public Server.Listener ObjectUnderTest;

			public override string ToString()
			{
				return $"{this.Name}";
			}
		}
#endregion

#region Test data
//=========================================================================================================================
//Please modify this section only in the Modeleditor not here in the code, because otherwise it will cause merge conflicts!
//=========================================================================================================================
		public class ExpectedReturnValueTests : TheoryData<NoThrowTestData>
		{
			public ExpectedReturnValueTests()
			{
				this.Add(new NoThrowTestData
				{
					Name = @"p1",
					ObjectUnderTest = null
				});
				this.Add(new NoThrowTestData
				{
					Name = @"p2",
					ObjectUnderTest = null
				});
				this.Add(new NoThrowTestData
				{
					Name = @"p3",
					ObjectUnderTest = new Server.Listener()
				});
			}
		}
#endregion
	}
}

/*
WARNING: Modification of this comment will make it impossible to merge user-defined changes

BEGIN_CODEGEN_DATA
H4sIAAAAAAAAAO2U348SMRDHn5eE/2FEH5bLASdLNB6e0cCdXiJgZDUa40PZzh41pSVtF9xc+N+d7nJwcD8eTAwvkg2
ZTqfznXY+beuoWjmC/giGoxgGo/7lxXeIP1yOoTcaDM6HsZ99jwoNc8hhkgPHxYxs74/ROphpjvIUovaLdtTuvGx02i
dpo5NE2HjFOrxxwrCdREkUsUlKa1rVSrWSWaGuYJxbh7Pu7rDZ01Ji4oRWtlnoimQT8i1TwnV9BsVmaOcsQRijWaDxl
dhq5bpaCebZRIoEEsmshbFjxvUxZZl0PqbHLFUeUNxTg1ckAvEUtRFIi4PgRzHIfxZ2zyfoM8dCl89Rp+H57zkVhvwz
usyor0xmWMjW68WCte5CC35HNhzqeGr00ts+JXD6q/tVvuIg8MPmaPKL8n9RvNxO83aSsN71gSuqGxUvS/fnsNkFlUh
baLXODvXz4p8k0vl6IkSag5sKC7bsJWglcxCKnAgDTwxy4bQBpR1M0eDNXEJzxzDBhGWUSZPLLAVZwsFSSAmlf4bmys
eqlI7c2ScH3vmm+daZLHGw1+1tn7dhHuchQdy97S9Zbn4UdBOIfNgjoiB/G60p1giON+liPS6MsABrrRiYglZ4Vrv2/
Wh6zVWtVF09jpS/3Lwo/z9WB9l5sPuWPfT+wGn5iOWetdd77L25A99DaXaxKWB5x3mocHkfz5vAwBMFZ/C2Nn9eO177
9sClaZVJWU6uyqfs7yTa/14iekyC0uxd0vWxbTTvu1R+TN8f69E2RWsHAAA=
END_CODEGEN_DATA
*/
