/*
* DO NOT MODIFY THIS COMMENT
* Generated by devmate
* Test model: 5d7e62b4-c800-4d75-baba-08679b78d4a5
*/

using System;
using System.Collections.Generic;
using System.Reflection;
using Microsoft.VisualStudio.TestTools.UnitTesting;

namespace ClientTests
{
	[TestClass]
	public class StartDefaultTestCase
	{
#region Test methods
		[DataTestMethod]
		[ExpectedReturnValueTests]
		public void StartDefaultTest(NoThrowTestData data)
		{
			data.ObjectUnderTest.StartDefault();
		}
#endregion

#region Types
//=========================================================================================================================
//Please modify this section only in the Modeleditor not here in the code, because otherwise it will cause merge conflicts!
//=========================================================================================================================
		public struct NoThrowTestData
		{
			public string Name;
			public Client.Receiver ObjectUnderTest;
		}
#endregion

#region Test data
//=========================================================================================================================
//Please modify this section only in the Modeleditor not here in the code, because otherwise it will cause merge conflicts!
//=========================================================================================================================
		[AttributeUsage(AttributeTargets.Method)]
		private class ExpectedReturnValueTests : Attribute, ITestDataSource
		{
			public IEnumerable<object[]> GetData(MethodInfo methodInfo)
			{
				yield return new object[]
				{
					new NoThrowTestData
					{
						Name = @"p1",
						ObjectUnderTest = new Client.Receiver()
					}
				};
			}

			public string GetDisplayName(MethodInfo methodInfo, object[] data)
			{
				return ((NoThrowTestData)data[0]).Name;
			}
		}
#endregion
	}
}

/*
WARNING: Modification of this comment will make it impossible to merge user-defined changes

BEGIN_CODEGEN_DATA
H4sIAAAAAAAAAO1V32/aMBB+DhL/w617gQoCm9rSlXXaBGzjAZhKWmlCPDjxAZ6MjWwHhib+9/mSAB3ttMe+LEKJ74f
vvjt/Phrn5dI5dEcwHEUwGHX7n79D9LU/hs5oMOgNI7J+QYWGOeQQb4HjeunXpI/QOlhqjvIGLnkLr97GF/XkutmsX/
DWZT1mMas3r69a7+LWNb9gl35Po1wql1Ir1BzGW+tw2f5TDDtaSkyc0MqGWV6RnLrc4axwOVgGIjHa6pkLH4RNmRy7l
AsdEsBIa2nDeyUcSd65TRAUW6JdsQShIwWqzGbLpV/lUjChdUcya6deWqWxFAkkJMPYMeO6OGOpzHZ0mPWNCPyu1wbn
HlDREnQLzX24IJh0mWOkHGS6aabr/Vx5/Mjv0KVGPTCZYpY/sxYJ11rwJ/kqQx0tjN7QmgID968q7SLgQUBiOIp/+Oj
3iqMhv/BxkEq1TY47DxgVzzFTOw7wtyv0uBuN25d6KPk3ib6xxCwx24JbCAs2P3DQSm5BKK9EGBDzkAunDSjtYIEG97
bE22oQY8JSH0l7ldkIvxIONkJKyPVLNHPyVTPfcmdfvXDlh8O3zqSJg5PTPp7z0Y3IP/Rcbj/W55T29yRBsUYDJ4z4B
wWIwTxL958GL1K5nxCfnD/aOHV4b9kcKwcxYh6ps2E+Tar5wDBi7QdyMaL+NlvgBg5RatDfc2qsU5PgE2b1eyr1XWGx
xPc6Y89k+sH/D2R7Knn2vprpYtTRMhtDRZRgK1ByMBkGULiBfZDcXHgFZHmG5I88AiI33MLHs9Wbs9peeUJob6dIJ7S
vVAv3Xf7d5XdkR2R/coeoNGFXkm0p4fMV1g5VHOfuHmhRauV0QlfJc9KcVsPjLd09c/9I9r/fPoWD4o4HAAA=
END_CODEGEN_DATA
*/
